package main

import (
	"fmt"
	"strconv"
)

func strUnCompress(s string, pos *int) string {
	res := ""
	countStartPos := 0
	curCount := 0
	curCompStr := ""
	unCompressing := false
	for *pos < len(s) {
		if string(s[*pos]) == "[" {
			unCompressing = true
			countStartPos = *pos + 1
		} else if string(s[*pos]) == "]" {
			break
		} else if string(s[*pos]) == "|" {
			curCount, _ = strconv.Atoi(s[countStartPos:*pos])
			*pos++
			curCompStr = strUnCompress(s, pos)
			for j := 0; j < curCount; j++ {
				res += curCompStr
			}
			unCompressing = false
		} else {
			if !unCompressing {
				res += string(s[*pos])
			}
		}
		*pos++
	}
	return res
}

func main() {
	res := "BHCJSBCSCWDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWFDASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWP"
	pos := 0
	unStr := strUnCompress("BHCJSBCSCW[100|DASKDNKJWDNWCNQWCNOQCNQWOICNWQOINCWQOICNQWOIXWOISWIODAOWPQWDMQKOQZCDWF]WQJDWQUINCQQW[99|SDWQJCIQIUWCNQUCNWQIDNWQUIFNSALQP]DQOJOIXZALPPQQAAX", &pos)
	fmt.Println(res)
	fmt.Println(unStr)
	fmt.Println(res == unStr)
}
